language: go

sudo: false

cache:
  apt: true
  directories:
  - bin

dist: trusty

env:
  HUGO_BUILD_TAGS="extended"
  
git:
  depth: false
  
go:
  - "1.10.2"

os:
  - linux  

# 分支白名单限制: 只有hugo分支的提交才会触发构建
branches:
  only:
    - hugo
    
matrix:
  allow_failures:
    - go: tip
  fast_finish: true
   
before_install:
- openssl aes-256-cbc -K $encrypted_e83dbcce0b4d_key -iv $encrypted_e83dbcce0b4d_iv
  -in .travis/hugo_rsa.enc -out ~/.ssh/hugo_rsa -d
- chmod 600 ~/.ssh/hugo_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/hugo_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name "Jinlong Quan"
- git config --global user.email "ovwane@gmail.com"

install:
  - cd $TRAVIS_BUILD_DIR
  - wget https://github.com/gohugoio/hugo/releases/download/v0.44/hugo_0.44_Linux-64bit.tar.gz -O /tmp/hugo.tar.gz
  - mkdir -p bin
  - tar -xvf /tmp/hugo.tar.gz -C bin
  - chmod +x bin/hugo
  - export PATH=$PATH:$TRAVIS_BUILD_DIR/bin
  - git clone -b gh-pages https://github.com/ovwane/hugo $TRAVIS_BUILD_DIR/public
  
script:
  - cd $TRAVIS_BUILD_DIR
  - hugo version
  - hugo -D
  - cd $TRAVIS_BUILD_DIR/public
  - msg="rebuilding site `date`"
  - git add -A
  - git commit -m "$msg"
  - git push origin gh-pages
 
after_success:
- echo "OK!网站部署成功啦！"
